### ISSUE TITLE
Be able to send approval workflow to non Google users

### ISSUE THREAD

**Issue by St3ph-fr** [St3ph-fr/ezflow#2]
For now it is only possible to send approval workflow to users which have edit rights to the Google Docs.

**Comment by mlazzje** [comment]
Added in the next release.

When you create a workflow, you'll be able to add a non Google user as validator.

![image](https://cloud.githubusercontent.com/assets/5486652/22266517/97c5840a-e280-11e6-849a-168041c37473.png)

He will receive a link, with a note, and the version to validate as PDF attached to the mail.

![image](https://cloud.githubusercontent.com/assets/5486652/22266605/eebeccd0-e280-11e6-9e80-26a2ebc2ca76.png)

The link will redirect him to a webpage like this:
